---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: articles
  name: articles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: articles
    spec:
      containers:
      - image: public.ecr.aws/flynshue/articles:v0.1.2
        name: articles
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: articles
  name: articles
spec:
  ports:
  - name: 8080-5000
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: articles
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: articles
  name: articles
spec:
  host: ""
  port:
    targetPort: 8080-5000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: articles
    weight: 100
  wildcardPolicy: None

