---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: articles
  name: articles
spec:
  replicas: 3
  selector:
    matchLabels:
      app: articles
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: articles
    spec:
      containers:
      - image: public.ecr.aws/flynshue/articles:v0.2.2
        name: articles
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: articles
  name: articles
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: articles
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: articles
  name: articles
spec:
  host: ""
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: articles
    weight: 100
  wildcardPolicy: None

