{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "articles.labels" . | nindent 4 }}
  name: {{ include "articles.fullname" . }}
spec:
  host: ""
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: articles
    weight: 100
  wildcardPolicy: None
{{- end }}